image: docker:dind

variables:
  DOCKER_DRIVER: overlay

services:
- docker:dind

stages:
- build
- package
- deploy

build:
  image: openjdk:11-jdk
  stage: build
  tags:
    - dokcer
  script:
    - ./gradlew build
  artifacts:
    paths:
      - build/libs/*.jar
      - build/resources

docker-dev:
  environment: development
  stage: package
  tags:
    - dokcer
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - docker build -t $CI_REGISTRY_IMAGE:dev-latest .
    - docker push $CI_REGISTRY_IMAGE:dev-latest
  only:
    - develop

docker-test:
  environment: test
  stage: package
  tags:
    - dokcer
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - docker build -t $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:latest
  only:
    - master

deploy-test:
  image: debian
  environment: test
  stage: deploy
  tags:
    - dokcer
  script:
    - apt-get update -qy
    - apt-get install -y curl build-essential
    - curl -X POST -F token=$TRIGGER_TOKEN -F ref=master https://gitlab.com/api/v4/projects/12440227/trigger/pipeline
  only:
    - master

docker-prod:
  stage: package
  environment: prod
  tags:
    - dokcer
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - echo "$CI_COMMIT_REF_NAME $CI_PIPELINE_ID" > buildversion.txt
    - docker build -t $CI_REGISTRY_IMAGE:prod-latest .
    - docker tag $CI_REGISTRY_IMAGE:prod-latest $CI_REGISTRY_IMAGE:prod-latest
    - docker tag $CI_REGISTRY_IMAGE:prod-latest $CI_REGISTRY_IMAGE:prod-$CI_COMMIT_REF_NAME
    - docker push $CI_REGISTRY_IMAGE:prod-latest
    - docker push $CI_REGISTRY_IMAGE:prod-$CI_COMMIT_REF_NAME
    
  only:
    - tags
    - prod